// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrizbmiywjjjhooofbrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yaXpibWl5d2pqamhvb29mYnJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5ODQ3MDAsImV4cCI6MjA2NDU2MDcwMH0.nUQiiOWGmodu6eClCh41aUYVDDesJhcDXyMDhqGbnhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);